### ISSUE TITLE
Question about teaching SQL lite

### ISSUE THREAD

**Issue by lwasser** [datacarpentry/sql-ecology#17]
Hey Ethan, et al. I am working through the install instructions for SQL lite. 

The lesson, as written instructs students to install SQL as a plugin for firefox. I went through that and it is fairly straight forward. However the SWC setup instructions suggest that Sql comes installed with OSX natively but there is a windows installer.

http://ouinformatics.github.io/2015-04-15-ncar/  <see instructions at very bottom>

How is SQLlite normally taught? Should we ask students to go the firefox route? Or is there a gui version of the database that runs independently of the firefox browser. 

Thank you for any feedback.
Leah

**Comment by ethanwhite** [comment]
I always teach SQLite using the Firefox plugin as do many SWC instructors. It's the easiest free option I've come across. The SWC setup instructions mentioning that SQLite is included with some operating systems is referring to `sqlite3`, which is a command line utility. In my opinion it is a very difficult interface for novices, especially since Data Carpentry will not be spending a lot of time in the shell. There are other GUIs certainly, but many of them cost money and the last time I explored them the free ones weren't cross platform. So, I think we should use the Firefox plugin. It's been heavily tested in SWC and everyone can get Firefox and an add-on installed successfully.

**Comment by lwasser** [comment]
Thank you, Ethan. That is very helpful. Firefox plugin it is.
